sudo: false
language: python

python:
  - "2.7"

addons:
  apt:
    packages:
      - python-lxml

install:
  - pip2 install service_identity
  - pip2 install pymongo
  - pip2 install scrapy

script: nosetests

matrix:
  exclude:
    - python: "3.3"
    - python: "3.4"