language: python

python:
  - "2.7"

before_install:
  - sudo apt-get install python-lxml
  - pip2 install service_identity
  - pip2 install pymongo
  - pip2 install scrapy

matrix:
  exclude:
    - python: "3.3"
    - python: "3.4"